### ISSUE TITLE
Is there any way to adjust the bpp?

### ISSUE THREAD

**Issue by RuixiangXue** [StevenWang30/R-PCC#3]

**Comment by StevenWang30** [comment]
Bpp will be influenced by the reconstruction accuracy. You can modify the "accuracy: 0.02" in the .yaml cfg file to change the bpp.

**Comment by RuixiangXue** [comment]
thank  u@StevenWang30  very much,another question is that Does the example.bin provided come from kitti raw scan and any preprocess?

**Comment by StevenWang30** [comment]
Yes, the example.bin is from KITTI raw data without any preprocessing.
