### ISSUE TITLE
Missing velodyne point clouds in the cloud drive

### ISSUE THREAD

**Issue by JAS0NN** [StevenWang30/R-PCC#4]
Thanks for your awesome work!

BTW, I found that the tested point clouds in the `KITTI_rawdata` folder from the cloud drive is missing.

Is it convenient for you if you upload these files again? Thanks!

**Comment by StevenWang30** [comment]
Sorry for the inconvenience.
I have updated all of the data in the onedrive link, plz check it. If there are any questions, feel free to contact me.
