### ISSUE TITLE
About the figure 7. in the R-PCC paper  

### ISSUE THREAD

**Issue by JAS0NN** [StevenWang30/R-PCC#5]
Thanks for your great work!

I am interested about the software or library you used to show the reconstruction error in figure 7. 
Is that figure drawn by the open3d in your released code? 

Thanks!

**Comment by StevenWang30** [comment]
Yes. 
You can check the func `draw_qualitative_point_clouds` in `utils/visualize_utils.py `

**Comment by JAS0NN** [comment]
Thanks for your reply.
